name: Deploy to GitHub Pages


run-name: Deploy to GitHub Pages
on:
  [push]
jobs:
  deploy-documentation:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm install
      - run: npm build

      - name: deploy
       uses: peaceiris/actions-gh-pages@v3.9.3
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./packages