name: Deploy to GitHub Pages


run-name: Deploy to GitHub Pages
on:
  [push]
jobs:
  build-an-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
        with:
          persist-credentials: false

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: Install and Build 
         run: npm install
         run: npm build

      - name: deploy
       uses: peaceiris/actions-gh-pages@v3.9.3
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: build