
name: Build and deploy to Github pages

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
      
jobs:
  build-deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: true 
      - name: Install 
        run: | 
          npm install
          cd example 
          npm install
      - name: Build 
        run:  |
          cd example
          npm run build:prod
      - name: Deploy to GH Pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/dist